name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Run unit tests
        run: ./gradlew test
      - name: Security Scan
        run: trivy fs ./app
      - name: Build & Push Docker Image
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest ${{ secrets.ECR_URI }}/myapp:latest
          docker push ${{ secrets.ECR_URI }}/myapp:latest
